<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="18" failed="12" ignored="4" total="38" passed="4">
  <reporter-output>
    <line>
      <![CDATA[Test_0 Class Started...]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Passed]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Passed]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[Test_0 Test Finished.]]>
    </line>
    <line>
      <![CDATA[Test_1 Class Started...]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Passed]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Passed]]>
    </line>
    <line>
      <![CDATA[CaptureScreen method called]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Started ]]>
    </line>
    <line>
      <![CDATA[goToFacebook Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Started ]]>
    </line>
    <line>
      <![CDATA[goToGoogle Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYahoo Test Failed...java.lang.NullPointerException]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Started ]]>
    </line>
    <line>
      <![CDATA[goToYouTube Test Failed...java.lang.NullPointerException]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="209803" started-at="2019-10-04T06:23:22Z" finished-at="2019-10-04T06:26:52Z">
    <groups>
    </groups>
    <test name="Test_0" duration-ms="166314" started-at="2019-10-04T06:23:22Z" finished-at="2019-10-04T06:26:08Z">
      <class name="core.test_scripts.Test_1">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeTest" is-config="true" duration-ms="2525" started-at="2019-10-04T06:23:22Z" finished-at="2019-10-04T06:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeClass" is-config="true" duration-ms="4" started-at="2019-10-04T06:23:24Z" finished-at="2019-10-04T06:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="19" started-at="2019-10-04T06:23:24Z" finished-at="2019-10-04T06:23:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToFacebook" duration-ms="9733" started-at="2019-10-04T06:23:24Z" finished-at="2019-10-04T06:23:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToFacebook(Test_1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="356" started-at="2019-10-04T06:23:34Z" finished-at="2019-10-04T06:23:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_1.goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:23:35Z" finished-at="2019-10-04T06:23:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToFacebook" duration-ms="6753" started-at="2019-10-04T06:23:35Z" finished-at="2019-10-04T06:23:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToFacebook(Test_1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="40" started-at="2019-10-04T06:23:41Z" finished-at="2019-10-04T06:23:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_1.goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:23:41Z" finished-at="2019-10-04T06:23:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToFacebook" duration-ms="6111" started-at="2019-10-04T06:23:41Z" finished-at="2019-10-04T06:23:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToFacebook(Test_1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="30" started-at="2019-10-04T06:23:47Z" finished-at="2019-10-04T06:23:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_1.goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:23:47Z" finished-at="2019-10-04T06:23:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToFacebook" duration-ms="6022" started-at="2019-10-04T06:23:47Z" finished-at="2019-10-04T06:23:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToFacebook(Test_1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="664" started-at="2019-10-04T06:23:54Z" finished-at="2019-10-04T06:23:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=FAILURE method=Test_1.goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToGoogle" duration-ms="7066" started-at="2019-10-04T06:23:54Z" finished-at="2019-10-04T06:24:01Z">
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:23:54Z" finished-at="2019-10-04T06:23:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="499" started-at="2019-10-04T06:24:01Z" finished-at="2019-10-04T06:24:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=SUCCESS method=Test_1.goToGoogle()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:24:02Z" finished-at="2019-10-04T06:24:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToYahoo" duration-ms="32292" started-at="2019-10-04T06:24:02Z" finished-at="2019-10-04T06:24:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToYahoo(Test_1.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="28" started-at="2019-10-04T06:24:34Z" finished-at="2019-10-04T06:24:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_1.goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:24:34Z" finished-at="2019-10-04T06:24:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToYahoo" duration-ms="8240" started-at="2019-10-04T06:24:34Z" finished-at="2019-10-04T06:24:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToYahoo(Test_1.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="33" started-at="2019-10-04T06:24:42Z" finished-at="2019-10-04T06:24:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_1.goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:24:42Z" finished-at="2019-10-04T06:24:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToYahoo" duration-ms="7936" started-at="2019-10-04T06:24:42Z" finished-at="2019-10-04T06:24:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToYahoo(Test_1.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="28" started-at="2019-10-04T06:24:50Z" finished-at="2019-10-04T06:24:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_1.goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:24:50Z" finished-at="2019-10-04T06:24:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToYahoo" duration-ms="66026" started-at="2019-10-04T06:24:50Z" finished-at="2019-10-04T06:25:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToYahoo(Test_1.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="1513" started-at="2019-10-04T06:25:56Z" finished-at="2019-10-04T06:25:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=FAILURE method=Test_1.goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:25:58Z" finished-at="2019-10-04T06:25:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="goToYouTube" duration-ms="8213" started-at="2019-10-04T06:25:58Z" finished-at="2019-10-04T06:26:06Z">
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterMethod" is-config="true" duration-ms="1174" started-at="2019-10-04T06:26:06Z" finished-at="2019-10-04T06:26:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=SUCCESS method=Test_1.goToYouTube()[pri:0, instance:core.test_scripts.Test_1@6eebc39e] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:core.test_scripts.Test_1@6eebc39e]" name="afterClass" is-config="true" duration-ms="251" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- core.test_scripts.Test_1 -->
      <class name="core.test_scripts.Test_2">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="24" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_2.goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToFacebook" duration-ms="0" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:07Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToFacebook(Test_2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:07Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToFacebook" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToFacebook(Test_2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="31" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_2.goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToFacebook" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToFacebook(Test_2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="40" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=SKIP method=Test_2.goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToFacebook" duration-ms="2" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToFacebook(Test_2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="37" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=FAILURE method=Test_2.goToFacebook()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToGoogle" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToGoogle(Test_2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="34" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=SKIP method=Test_2.goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToGoogle" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToGoogle(Test_2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="46" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=SKIP method=Test_2.goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToGoogle" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToGoogle(Test_2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="47" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=SKIP method=Test_2.goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="2" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToGoogle" duration-ms="2" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToGoogle(Test_2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="51" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=FAILURE method=Test_2.goToGoogle()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYahoo" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYahoo(Test_2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="43" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_2.goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYahoo" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYahoo(Test_2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="38" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_2.goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYahoo" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYahoo(Test_2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="38" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=SKIP method=Test_2.goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYahoo" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYahoo(Test_2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="32" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=FAILURE method=Test_2.goToYahoo()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYouTube" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYouTube(Test_2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="35" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=SKIP method=Test_2.goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="44" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=SKIP method=Test_2.goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYouTube" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYouTube(Test_2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="SKIP" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYouTube" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYouTube(Test_2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Skipped...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="36" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=SKIP method=Test_2.goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="goToYouTube" duration-ms="2" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYouTube(Test_2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterMethod" is-config="true" duration-ms="41" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=FAILURE method=Test_2.goToYouTube()[pri:0, instance:core.test_scripts.Test_2@464bee09] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:core.test_scripts.Test_2@464bee09]" name="afterClass" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- core.test_scripts.Test_2 -->
    </test> <!-- Test_0 -->
    <test name="Test_1" duration-ms="43217" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:52Z">
      <class name="core.test_scripts.Test_1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeSuite" is-config="true" duration-ms="111" started-at="2019-10-04T06:23:22Z" finished-at="2019-10-04T06:23:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeTest" is-config="true" duration-ms="1285" started-at="2019-10-04T06:26:08Z" finished-at="2019-10-04T06:26:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeClass" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:10Z" finished-at="2019-10-04T06:26:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="goToFacebook" duration-ms="9205" started-at="2019-10-04T06:26:10Z" finished-at="2019-10-04T06:26:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToFacebook(Test_1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:10Z" finished-at="2019-10-04T06:26:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="afterMethod" is-config="true" duration-ms="600" started-at="2019-10-04T06:26:19Z" finished-at="2019-10-04T06:26:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=FAILURE method=Test_1.goToFacebook()[pri:0, instance:core.test_scripts.Test_1@6e06451e] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="goToGoogle" duration-ms="5999" started-at="2019-10-04T06:26:19Z" finished-at="2019-10-04T06:26:25Z">
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:19Z" finished-at="2019-10-04T06:26:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="afterMethod" is-config="true" duration-ms="492" started-at="2019-10-04T06:26:25Z" finished-at="2019-10-04T06:26:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=SUCCESS method=Test_1.goToGoogle()[pri:0, instance:core.test_scripts.Test_1@6e06451e] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:26Z" finished-at="2019-10-04T06:26:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="goToYahoo" duration-ms="14529" started-at="2019-10-04T06:26:26Z" finished-at="2019-10-04T06:26:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at core.helpers.assertion.AssertionHelper.makeFalse(AssertionHelper.java:32)
at core.test_scripts.Test_1.goToYahoo(Test_1.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Failed...java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="afterMethod" is-config="true" duration-ms="1434" started-at="2019-10-04T06:26:41Z" finished-at="2019-10-04T06:26:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=FAILURE method=Test_1.goToYahoo()[pri:0, instance:core.test_scripts.Test_1@6e06451e] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:42Z" finished-at="2019-10-04T06:26:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_1.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="goToYouTube" duration-ms="8177" started-at="2019-10-04T06:26:42Z" finished-at="2019-10-04T06:26:50Z">
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="afterMethod" is-config="true" duration-ms="1206" started-at="2019-10-04T06:26:50Z" finished-at="2019-10-04T06:26:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=SUCCESS method=Test_1.goToYouTube()[pri:0, instance:core.test_scripts.Test_1@6e06451e] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[CaptureScreen method called]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:core.test_scripts.Test_1@6e06451e]" name="afterClass" is-config="true" duration-ms="188" started-at="2019-10-04T06:26:51Z" finished-at="2019-10-04T06:26:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- core.test_scripts.Test_1 -->
      <class name="core.test_scripts.Test_2">
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToFacebook() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="goToFacebook()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="goToFacebook" duration-ms="1" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToFacebook(Test_2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToFacebook Test Started ]]>
            </line>
            <line>
              <![CDATA[goToFacebook Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToFacebook -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="afterMethod" is-config="true" duration-ms="20" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToFacebook status=FAILURE method=Test_2.goToFacebook()[pri:0, instance:core.test_scripts.Test_2@59494225] output=goToFacebook Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToGoogle() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToGoogle()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="goToGoogle" duration-ms="0" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToGoogle(Test_2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToGoogle Test Started ]]>
            </line>
            <line>
              <![CDATA[goToGoogle Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToGoogle -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="afterMethod" is-config="true" duration-ms="21" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToGoogle status=FAILURE method=Test_2.goToGoogle()[pri:0, instance:core.test_scripts.Test_2@59494225] output=goToGoogle Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYahoo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYahoo()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="goToYahoo" duration-ms="0" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYahoo(Test_2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYahoo Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYahoo Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYahoo -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="afterMethod" is-config="true" duration-ms="23" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYahoo status=FAILURE method=Test_2.goToYahoo()[pri:0, instance:core.test_scripts.Test_2@59494225] output=goToYahoo Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void core.test_scripts.Test_2.goToYouTube() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="goToYouTube()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="goToYouTube" duration-ms="1" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.test_scripts.Test_2.goToYouTube(Test_2.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[goToYouTube Test Started ]]>
            </line>
            <line>
              <![CDATA[goToYouTube Test Failed...java.lang.NullPointerException]]>
            </line>
          </reporter-output>
        </test-method> <!-- goToYouTube -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:core.test_scripts.Test_2@59494225]" name="afterMethod" is-config="true" duration-ms="23" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=goToYouTube status=FAILURE method=Test_2.goToYouTube()[pri:0, instance:core.test_scripts.Test_2@59494225] output=goToYouTube Test Started ]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:core.test_scripts.Test_2@59494225]" name="afterClass" is-config="true" duration-ms="1" started-at="2019-10-04T06:26:52Z" finished-at="2019-10-04T06:26:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- core.test_scripts.Test_2 -->
    </test> <!-- Test_1 -->
  </suite> <!-- Suite -->
</testng-results>
